[build]
    publish = "build/html"
    command = "make html"

[context.production.environment]
  ALGOLIA_APP_ID = "0PX8BTWD6K"
  ALGOLIA_INDEX_PREFIX = "red_"
  ALGOLIA_INDICES = "in,through,out"

# Add these lines to exclude secrets from scanning
[secrets]
  scan_omit_paths = ["build/doctrees/", "*.pickle"]
  scan_omit_keys = ["ALGOLIA_API_KEY"]  # Only if absolutely needed
