[build]
  publish = "build/html"
  command = "make clean && make html"  # Simplified command

[build.environment]
  NODE_VERSION = "18.17.1"  # or "20" for latest LTS

[functions]
  node_bundler = "esbuild"  # Recommended bundler

[context.production.environment]
  ALGOLIA_APP_ID = "0PX8BTWD6K"
  ALGOLIA_INDEX_PREFIX = "red_"
  ALGOLIA_INDICES = "in,through,out"
  SPHINX_DISABLE_PICKLE = "1"

[secrets]
  scan_omit_paths = ["build/doctrees", "build/*.pickle"]  # Simplified paths
