[build]
  publish = "build/html"
  command = "make clean && make html"

[context.production.environment]
  ALGOLIA_APP_ID = "0PX8BTWD6K"  # This is public-safe
  ALGOLIA_INDEX_PREFIX = "red_"
  ALGOLIA_INDICES = "in,through,out"

[secrets]
  scan_omit_paths = ["build/doctrees/", "build/*.pickle"]
