[build]
  publish = "build/html"
  command = "make clean && make html"

[build.environment]
  NODE_VERSION = "18.17.1"
  ALGOLIA_APP_ID = "0PX8BTWD6K"
  ALGOLIA_INDEX_PREFIX = "red_"
  ALGOLIA_INDICES = "in,through,out"
  SPHINX_DISABLE_PICKLE = "1"

[functions]
  node_bundler = "esbuild"

[secrets]
  scan_omit_paths = ["build/doctrees", "build/*.pickle"]
